# Generated by Django 4.2.9 on 2026-02-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumni",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("batch", models.CharField(max_length=10)),
                ("profession", models.CharField(blank=True, max_length=200)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="alumni/"),
                ),
                ("achievement", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Alumni",
                "verbose_name_plural": "Alumni",
                "ordering": ["-batch"],
            },
        ),
    ]
