# Generated by Django 4.2.9 on 2026-02-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=200)),
                ("student_class", models.CharField(max_length=50)),
                ("father_name", models.CharField(max_length=200)),
                ("admission_no", models.CharField(max_length=50, unique=True)),
                ("tc_number", models.CharField(max_length=50, unique=True)),
                (
                    "pdf_upload",
                    models.FileField(blank=True, null=True, upload_to="tc/pdfs/"),
                ),
                ("issue_date", models.DateField()),
            ],
            options={
                "verbose_name": "Transfer Certificate",
                "verbose_name_plural": "Transfer Certificates",
            },
        ),
    ]
