# Generated by Django 4.2.9 on 2026-02-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(
                        default="Little Flower Children School", max_length=200
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True, default="Excellence in Education", max_length=300
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        default="LFCS",
                        help_text="Short name shown in navbar e.g. LFCS",
                        max_length=20,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Navbar logo image",
                        null=True,
                        upload_to="site/",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="Browser tab icon (32×32 .ico or .png)",
                        null=True,
                        upload_to="site/",
                    ),
                ),
                ("established_year", models.CharField(default="2000", max_length=10)),
                (
                    "primary_color",
                    models.CharField(
                        default="#1a3c6b",
                        help_text="Hex code e.g. #1a3c6b",
                        max_length=10,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#e8a020",
                        help_text="Hex code e.g. #e8a020",
                        max_length=10,
                    ),
                ),
                (
                    "footer_text",
                    models.CharField(
                        blank=True,
                        help_text="Short text shown in footer",
                        max_length=400,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
