# Generated by Django 4.2.9 on 2026-02-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PublicDisclosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("document_pdf", models.FileField(upload_to="disclosure/pdfs/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("financial", "Financial"),
                            ("academic", "Academic"),
                            ("infrastructure", "Infrastructure"),
                            ("cbse", "CBSE"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("publish_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Public Disclosure",
                "verbose_name_plural": "Public Disclosures",
                "ordering": ["-publish_date"],
            },
        ),
    ]
