# Generated by Django 4.2.9 on 2026-02-25 08:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DirectorMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("photo", models.ImageField(upload_to="messages/director/")),
                ("message", ckeditor.fields.RichTextField()),
                ("designation", models.CharField(default="Director", max_length=200)),
            ],
            options={
                "verbose_name": "Director's Message",
                "verbose_name_plural": "Director's Message",
            },
        ),
        migrations.CreateModel(
            name="PrincipalMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("photo", models.ImageField(upload_to="messages/principal/")),
                ("message", ckeditor.fields.RichTextField()),
                ("qualification", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Principal's Message",
                "verbose_name_plural": "Principal's Message",
            },
        ),
    ]
