# Generated by Django 5.2.11 on 2026-02-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtube_link',
            field=models.CharField(help_text="Just copy and paste the FULL YouTube link from your browser address bar or the 'Share' button. (e.g., https://www.youtube.com/watch?v=...) Do NOT paste iframe embed code.", max_length=300),
        ),
    ]
