# Generated by Django 4.2.9 on 2026-02-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("designation", models.CharField(max_length=200)),
                ("qualification", models.CharField(blank=True, max_length=200)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="staff/")),
                ("experience", models.CharField(blank=True, max_length=100)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("management", "Management"),
                            ("science", "Science"),
                            ("maths", "Mathematics"),
                            ("english", "English"),
                            ("social", "Social Studies"),
                            ("hindi", "Hindi"),
                            ("computer", "Computer Science"),
                            ("arts", "Arts & Crafts"),
                            ("sports", "Sports & PE"),
                            ("administration", "Administration"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Member",
                "verbose_name_plural": "Staff Members",
                "ordering": ["department", "name"],
            },
        ),
    ]
