# Generated by Django 4.2.9 on 2026-02-25 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CareerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("qualification", models.CharField(max_length=200)),
                ("experience", models.CharField(blank=True, max_length=100)),
                ("resume_upload", models.FileField(upload_to="career/resumes/")),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("applied_for", models.CharField(max_length=200)),
                ("applied_on", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Career Application",
                "verbose_name_plural": "Career Applications",
                "ordering": ["-applied_on"],
            },
        ),
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("message", models.TextField()),
                ("class_interested", models.CharField(blank=True, max_length=50)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("replied", "Replied"),
                            ("resolved", "Resolved"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("reply", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Enquiry",
                "verbose_name_plural": "Enquiries",
                "ordering": ["-date"],
            },
        ),
    ]
