# Generated by Django 4.2.9 on 2026-02-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prospectus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=10)),
                ("pdf_file", models.FileField(upload_to="prospectus/")),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Prospectus",
                "verbose_name_plural": "Prospectus",
                "ordering": ["-year"],
            },
        ),
    ]
