# Generated by Django 4.2.9 on 2026-02-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SchoolCaptain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "student_class",
                    models.CharField(max_length=50, verbose_name="Class"),
                ),
                ("photo", models.ImageField(upload_to="captain/")),
                ("message", models.TextField(blank=True)),
                ("year", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "School Captain",
                "verbose_name_plural": "School Captains",
                "ordering": ["-year"],
            },
        ),
    ]
