# Generated by Django 4.2.9 on 2026-02-25 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("house_name", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=50)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="house/logos/"),
                ),
            ],
            options={
                "verbose_name": "House",
                "verbose_name_plural": "Houses",
            },
        ),
        migrations.CreateModel(
            name="HouseLeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("head_boy", models.CharField(max_length=200)),
                ("head_girl", models.CharField(max_length=200)),
                ("vice_head_boy", models.CharField(blank=True, max_length=200)),
                ("vice_head_girl", models.CharField(blank=True, max_length=200)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="house/leaders/"
                    ),
                ),
                ("year", models.CharField(max_length=10)),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaders",
                        to="house.house",
                    ),
                ),
            ],
            options={
                "verbose_name": "House Leader",
                "verbose_name_plural": "House Leaders",
            },
        ),
    ]
