# Generated by Django 4.2.9 on 2026-02-25 08:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("pdf_upload", models.FileField(upload_to="academics/calendars/")),
                ("year", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "verbose_name": "Academic Calendar",
                "verbose_name_plural": "Academic Calendars",
            },
        ),
        migrations.CreateModel(
            name="AdmissionProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", ckeditor.fields.RichTextField()),
                (
                    "pdf_upload",
                    models.FileField(
                        blank=True, null=True, upload_to="academics/admission/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Admission Process",
                "verbose_name_plural": "Admission Process",
            },
        ),
        migrations.CreateModel(
            name="BookList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=100)),
                ("pdf_upload", models.FileField(upload_to="academics/booklists/")),
            ],
            options={
                "verbose_name": "Book List",
                "verbose_name_plural": "Book Lists",
            },
        ),
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=100)),
                ("description", ckeditor.fields.RichTextField(blank=True)),
                (
                    "pdf_upload",
                    models.FileField(
                        blank=True, null=True, upload_to="academics/curriculum/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Curriculum",
                "verbose_name_plural": "Curricula",
            },
        ),
        migrations.CreateModel(
            name="FeeStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=100)),
                ("fee_details", ckeditor.fields.RichTextField(blank=True)),
                (
                    "pdf_upload",
                    models.FileField(
                        blank=True, null=True, upload_to="academics/fees/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fee Structure",
                "verbose_name_plural": "Fee Structures",
            },
        ),
    ]
