# Generated by Django 5.2.11 on 2026-02-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='pdf_upload',
        ),
        migrations.AddField(
            model_name='feestructure',
            name='file_upload',
            field=models.FileField(blank=True, help_text='Upload an image (JPG/PNG) or PDF of the fee structure.', null=True, upload_to='academics/fees/'),
        ),
    ]
