# Generated by Django 5.2.11 on 2026-02-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_remove_feestructure_pdf_upload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionprocess',
            name='pdf_upload',
        ),
        migrations.AddField(
            model_name='admissionprocess',
            name='file_upload',
            field=models.FileField(blank=True, help_text='Upload an image (JPG/PNG) or PDF for admission.', null=True, upload_to='academics/admission/'),
        ),
    ]
